### ISSUE TITLE
different instances

### ISSUE THREAD

**Issue by phrakon** [yii2tech/ar-role#10]
Hi. Just a question.
Is there a way to get array of Student and Instructor instances after $humans = Human::find()->all();

I feel need to use in the Human model something like

```
public static function instantiate($row) {
  switch($row['role']) {
   case 'student': {
    ...
    return new Student($row);
   }
    ....
 }
}
```
but the method generates extra queries. Don't understand how to do it clear and beatiful.

**Comment by klimov-paul** [comment]
You may query `Human` with role relations:

```php
Human::find()
    ->with(['student', 'instructor'])
    ->all();
```

and then convert list of `Human` models into the list of specific roles using condition like:

```php
if ($human->isRelationPopulated('student')) {
   ...
}
```

but such manipulations are far beyond the reach of ActiveRecord behavior, thus would not appear at this extension.
