### ISSUE TITLE
Issue with yii 2.0.14

### ISSUE THREAD

**Issue by simonevallana** [yii2tech/ar-role#12]
Enh #13618 in yii2 2.0.14 breaks ar-role behavior

For example, in AfterInsert event I cannot reach role attributes anymore.

**Comment by klimov-paul** [comment]
Confirmed.
This is most likely caused by https://github.com/yiisoft/yii2/pull/13618

**Comment by klimov-paul** [comment]
Issue affects only owner-master roles.
The roles where owner is a slave are saved correctly.

**Comment by klimov-paul** [comment]
Resolved by commit e29dbf0b89e3598ed4e32331bb87a6f8dd9835b6
