### ISSUE TITLE
where() support?

### ISSUE THREAD

**Issue by luqmansungkar** [yii2tech/ar-role#5]
Hi,

I'm sorry I'm posting a question here, because I don't know where I should ask this.
I'm using this extension, and reading and updating data works fine. But when I want to use the where function as in `Models::find()->where()->all()` to filter the column in the related table, I get an error because the column is not in the main table.

Currently I only get it working using something like this:

``` php
->with([
  'relation_name' => function($query){
    $query->andWhere(['column_in_related_table' => 'value']);
  }
])
```

Is there any way of using it just like `Models::find()->where(['column_in_related_table' => 'value']))->all()` ?
If this is supported, where I might be wrong?

Thank you.

**Comment by klimov-paul** [comment]
You should use `joinWith()` to be able to add condition to both main and related table:

``` php
Student::find()
    ->joinWith('human')
    ->andWhere(['[[student]].group' => $group])
    ->andWhere(['[[human]].name' => $name])
    ->all();
```

**Comment by keeprock** [comment]
I think this should be a section in a documentation dedicated to this issue. I can help with it. @klimov-paul any thoughts?

**Comment by klimov-paul** [comment]
https://github.com/yii2tech/ar-role#querying-role-records-
