### ISSUE TITLE
Create new Student in Master role inheritance

### ISSUE THREAD

**Issue by makroxyz** [yii2tech/ar-role#9]
```php
$model = new Student();
$model->name = 'John Doe';
$model->address = 'Wall Street, 12';
$model->studyGroupId = 14;
$model->save(); // insert one record to the 'Human' table and one record - to the 'Student' table
```
this doesn't work in Master role inheritance... it doesn't create master record and throws \yii\db\Exception on Student's humanId column (null value in column "humanId" violates not-null constraint)

Is it right?

PS:
in RoleBehavior.php #286
```php
if (!$this->isOwnerSlave) {  // <-- this skips master model insert
    if (!empty($this->roleAttributes)) {
         foreach ($this->roleAttributes as $name => $value) {
             $this->owner->$name = $value;
         }
     }
     return; 
}
```

**Comment by klimov-paul** [comment]
Unable to reproduce. This case is covered by unit tests:
https://github.com/yii2tech/ar-role/blob/master/tests/RoleBehaviorTest.php#L113-L126
